### ISSUE TITLE
Make compatible with UAA 76 and higher 

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/uaa-customized-boshrelease#33]
Starting with uaa `76` - content security headers are now built into uaa and not configurable - https://github.com/cloudfoundry/uaa/pull/1981

## Notes

- This blocks the inline script in uaa-customized for login notice that requires click thru

## Acceptance Criteria

- [ ] Determine is this repo needs to exist in current form
- [ ] Determine the path forward if this repo to resolve the issue

**Comment by wz-gsa** [comment]
Confirmed with @jameshochadel that this is resolved. He contributed a change to UAA that made this configurable, and separately, I think we solved it by serving the script from the same domain so we didn’t get csp errors
